use serde::Deserialize;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WebhookEvents {
  BranchProtectionRule,
  CheckRun,
  CheckSuite,
  CodeScanningAlert,
  CommitComment,
  Create,
  Delete,
  Deployment,
  DeploymentStatus,
  DeployKey,
  Discussion,
  DiscussionComment,
  Fork,
  Gollum,
  Issues,
  IssueComment,
  Label,
  Member,
  Membership,
  Meta,
  Milestone,
  Organization,
  OrgBlock,
  Package,
  PageBuild,
  Project,
  ProjectCard,
  ProjectColumn,
  Public,
  PullRequest,
  PullRequestReview,
  PullRequestReviewComment,
  PullRequestReviewThread,
  Push,
  RegistryPackage,
  Release,
  Repository,
  RepositoryImport,
  RepositoryVulnerabilityAlert,
  SecretScanningAlert,
  Star,
  Status,
  Team,
  TeamAdd,
  Watch,
  WorkflowJob,
  WorkflowRun,
  #[serde(rename = "*")]
  All,
}
