[package]
name = "mol"
version = "0.1.0"
authors = ["Dmitry Dodzin <d.dodzin@gmail.com>"]
edition = "2018"
repository = "https://github.com/DmitryDodzin/mol"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo", "versioning", "changeset", "changesets"]

[[bin]]
name = "cargo-mol"

[features]
default = []

[dependencies]
mol-cargo = { path = 'crates/mol-cargo', version = "0.1" }
mol-core = { path = 'crates/mol-core', version = "0.1" }

anyhow = "1"
async-trait = "0.1"
clap = "3.0.0-beta.5"
dialoguer = "0.9"
faker_rand = "0.1"
lazy_static = "1"
rand = "0.8"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }

[workspace]
members = [
  "crates/*"
]

[profile.release]
opt-level = "s"
