[package]
name = "lightbringer"
version = "0.1.0"
authors = ["Dmitry Dodzin <d.dodzin@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
lightbringer-cargo = { path = './crates/lightbringer-cargo' }
lightbringer-core = { path = './crates/lightbringer-core' }

async-trait = "0.1"
clap = "3.0.0-beta.2"
dialoguer = "0.9"
failure = "0.1"
faker_rand = "0.1"
lazy_static = "1"
rand = "0.8"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }

[workspace]
members = [
  "crates/*"
]

[profile.release]
opt-level = "s"
