[package]
name = "mol-derive"
version = "0.1.0"
authors = ["Dmitry Dodzin <d.dodzin@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Mol Derive"
repository = "https://github.com/DmitryDodzin/mol"
readme = "README.md"

[lib]
proc-macro = true
